apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      run: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Mise a jour de nginx 1.10.2"
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:1.10.2
        name: nginx
